apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "4"
spec:
  version: v1.8.2
  server:
    route:
      enabled: true
  dex:
    image: ghcr.io/dexidp/dex
    openShiftOAuth: true
    version: v2.27.0
  resourceCustomizations: |
    route.openshift.io/Route:
      ignoreDifferences: |
        jsonPointers:
        - /spec/host
  rbac:
    defaultPolicy: ''
    policy: |
      g, ocp-admins, role:admin
      g, ocp-users, role:user
    scopes: '[groups]'
  initialRepositories: |
    - name: cluster-config
      type: git
      url: https://github.com/lebrisg/openshift-cluster-config
    - name: examples
      type: git
      url: https://github.com/christianh814/gitops-examples
